version: '3.8'

services:
  # PostgreSQL 데이터베이스 (포트 변경으로 충돌 해결)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"  # 포트 변경: 로컬 5433 → 컨테이너 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forte -d forte_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # FastAPI 백엔드
  backend:
    build: ./backend
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      postgres:
        condition: service_healthy

  # React 프론트엔드 (개발용)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_ENV: ${REACT_APP_ENV}
      REACT_APP_DEBUG: ${REACT_APP_DEBUG}
    depends_on:
      - backend

volumes:
  postgres_data: