version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: forte_db
      POSTGRES_USER: forte
      POSTGRES_PASSWORD: forte123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database_schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forte -d forte_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # FastAPI 백엔드
  backend:
    build: ./backend
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql://forte:forte123@postgres:5432/forte_db
      SECRET_KEY: forte-development-secret-key
      GEMINI_API_KEY: AIzaSyDgLF4iQ3DC3bpvEBmn_IOiDtPxKKWccOo
      DEBUG: "True"
      ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React 프론트엔드 (개발용)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_ENV: development
      REACT_APP_DEBUG: "true"
    depends_on:
      - backend

volumes:
  postgres_data: